### ISSUE TITLE
Changing dimensions when configuring external devices

### ISSUE THREAD

**Issue by berndporr** [google/science-journal#5]
The two ADC channels can be configured to measure V, mV (multiplied by 1000 for mV signals) and Ohm. For channel one I have: V and mV depending on the application. For biosignals (or small differential one) I set the PGA of the ADC to a higher value (x6) and I multiply the result by 1000 (see also my ECG).
![adc_config](https://cloud.githubusercontent.com/assets/1679394/19023112/018c6d2e-88de-11e6-9770-347c22c48535.png)
For channel 2 I have Volt or Ohm (essentially I switch on a 22uA bias current via the config menu and then one can measure resistance):
![adc2config](https://cloud.githubusercontent.com/assets/1679394/19023132/54f6f06a-88de-11e6-8944-6a18314d7e63.png)
I've got the impression that the dimensions are only read once and then stored in sciencejournal. Would it be possible to have these checked dynamically or perhaps move these to the observer and/or able to modify them after an config intent has happened?

**Comment by dsaff** [comment]
Yes, we should reload after configuration.

**Comment by whatsthebeef** [comment]
Any ideas when this might be implemented? I could look into it if you are accepting pull requests and haven't started working on it yet.

**Comment by dsaff** [comment]
@whatsthebeef, I expect a fix by Friday, if not sooner.  I would consider pull requests, but I'd recommend holding off; this particular area of the code is seeing a lot of churn right now.

**Comment by dsaff** [comment]
This should be, at last, fixed in master.  Please verify!

**Comment by berndporr** [comment]
Yes. Works! Thanks, @dsaff!

**Comment by berndporr** [comment]
Sorry guys. As you know in the sensor menu I can switch to mV, V or uV. That worked really well but now it's back to the problem that the first onSensorFound dimension stays. Here've switched in the sensor menu from V to uV but the plot still shows V:
![volt](https://cloud.githubusercontent.com/assets/1679394/20318750/6ebae428-ab63-11e6-8768-adbbc0a528b0.png)
```
I've added this debug output to my code:
                    c.onSensorFound("" + i, // sensorAddress = ch index number
                            channelDescr, // name
                            behaviour[i],
                            sensorAppearanceResources[i]);
                    if (Log.isLoggable(TAG, Log.DEBUG)) {
                        Log.d(TAG,String.format("onSensorFound:%s:%s",
                                sensorAppearanceResources[i].shortDescription,
                                sensorAppearanceResources[i].units));
                    }
                                    }
```
11-15 18:40:16.992 16532-16545/tech.glasgowneuro.attysplot D/Attys2ScienceJournal: onSensorFound:Acceleration X:m/s^2
11-15 18:40:16.993 16532-16545/tech.glasgowneuro.attysplot D/Attys2ScienceJournal: onSensorFound:Acceleration Y:m/s^2
11-15 18:40:16.993 16532-16545/tech.glasgowneuro.attysplot D/Attys2ScienceJournal: onSensorFound:Acceleration Z:m/s^2
11-15 18:40:16.994 16532-16545/tech.glasgowneuro.attysplot D/Attys2ScienceJournal: onSensorFound:Magnetic field X:µT
11-15 18:40:16.995 16532-16545/tech.glasgowneuro.attysplot D/Attys2ScienceJournal: onSensorFound:Magnetic field Y:µT
11-15 18:40:16.995 16532-16545/tech.glasgowneuro.attysplot D/Attys2ScienceJournal: onSensorFound:Magnetic field Z:µT
11-15 18:40:16.996 16532-16545/tech.glasgowneuro.attysplot D/Attys2ScienceJournal: onSensorFound:Analogue channel 1:µV
11-15 18:40:16.997 16532-16545/tech.glasgowneuro.attysplot D/Attys2ScienceJournal: onSensorFound:Analogue channel 2:V
Perhaps it needs to be updated via another call? I'm pretty sure it worked last week.

**Comment by berndporr** [comment]
P.S.: you see the same problem in my cropping example.

**Comment by dsaff** [comment]
Bernd,

Quick question; does the behavior change even when the appearance does not, or do they both get stuck?  Thanks,

   David

**Comment by berndporr** [comment]
It's recording V, mV or uV actually so the settings are correctly propagated to the onData call (I scale the data up there by x1,x1000,x1,000,000. It's just the appearance which won't change. It always shows as dimension (V).

**Comment by dsaff** [comment]
Thanks for the report; we're tracking the bug, and hope to have a fix posted very shortly.
